%TOKENS%

"+" = "tkPlus"
"-" = "tkMinus"
"IDENT" = "tkIdent"


%EBNF%

<Expression> ::= [<Sign>] <Designator> .

<Sign>       ::= "+" | "-" .

<Designator> ::= "IDENT" [ <Expression> ] .

